#ifndef  	_SET_IO_H
#define  	_SET_IO_H

#include  "sys.h"
#include  "set_io.h"

#define REY_1(n)		(n?HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,GPIO_PIN_RESET))
#define REY_2(n)		(n?HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,GPIO_PIN_RESET))
#define REY_3(n)		(n?HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11,GPIO_PIN_RESET))
#define REY_4(n)		(n?HAL_GPIO_WritePin(GPIOC,GPIO_PIN_12,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOC,GPIO_PIN_12,GPIO_PIN_RESET))
#define REY_5(n)		(n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET))
#define REY_6(n)		(n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_RESET))
#define REY_7(n)		(n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_RESET))
#define REY_8(n)		(n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_RESET))



#define DIR_L(n)		(n?HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,GPIO_PIN_RESET))
#define DIR_R(n)		(n?HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,GPIO_PIN_RESET))


void REY_io_init(void);
void REY_n(u8 i,u8 n);
void DIR_io_init(void);
#endif



